baseURL = 'https://QryptInc.github.io'
languageCode = 'en-us'
title = 'Qrypt'
theme = "hugo-theme-learn"
publishDir = "docs"
[params]
    themeVariant = "mine"
    disableLandingPageButton = true
    disableNextPrev = true
    disableLandingPage = true
    disableShortcutsTitle = true
[outputs]
    home = [ "HTML", "RSS", "JSON"]
[[menu.shortcuts]] 
    name = "<i class='fas fa-asterisk'></i> Qrypt Website"
    identifier = "ws"
    url = "https://www.qrypt.com/"
    weight = 1
[[menu.shortcuts]] 
    name = "<i class='fas fa-asterisk'></i> Qrypt Portal"
    identifier = "ps"
    url = "https://portal.qrypt.com/"
    weight = 2
[[menu.shortcuts]] 
    name = "<i class='fab fa-github'></i> Github Repo"
    identifier = "gh"
    url = "https://github.com/QryptInc/QryptInc.github.io"
    weight = 3